#!/bin/bash

code --install-extension DavidAnson.vscode-markdownlint
code --install-extension EditorConfig.EditorConfig
code --install-extension JakeWilson.vscode-cdnjs
code --install-extension PeterJausovec.vscode-docker
code --install-extension alefragnani.Bookmarks
code --install-extension bierner.color-info
code --install-extension christian-kohler.npm-intellisense
code --install-extension coolbear.systemd-unit-file
code --install-extension dbaeumer.vscode-eslint
code --install-extension djabraham.vscode-yaml-validation
code --install-extension donjayamanne.githistory
code --install-extension DotJoshJohnson.xml
code --install-extension doublefint.pgsql
code --install-extension ducksoupdev.Vue2
code --install-extension eamodio.gitlens
code --install-extension eg2.tslint
code --install-extension eg2.vscode-npm-script
code --install-extension eriklynd.json-tools
code --install-extension esbenp.prettier-vscode
code --install-extension felipecaputo.git-project-manager
code --install-extension foxundermoon.shell-format
code --install-extension johnpapa.Angular2
code --install-extension marcostazi.VS-code-vagrantfile
code --install-extension mauve.terraform
code --install-extension mechatroner.rainbow-csv
code --install-extension ms-mssql.mssql
code --install-extension ms-python.python
code --install-extension ms-vscode.csharp
code --install-extension ms-vscode.Go
code --install-extension ms-vscode.PowerShell
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension octref.vetur
code --install-extension robertohuertasm.vscode-icons
code --install-extension sdras.vue-vscode-snippets
code --install-extension shuworks.vscode-table-formatter
code --install-extension waderyan.gitblame
code --install-extension wayou.vscode-todo-highlight
code --install-extension wholroyd.jinja
